apiVersion : apps/v1
kind: Deployment
metadata:
  name: "board-api-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "appinno"
  template:
    metadata:
      labels:
        app: "appinno"
    spec:
      containers:
        - name: "board-api"
          image: "acrappinno.azurecr.io/board-api"
          ports:
          - containerPort: 80
