apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ghworkshop"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ghworkshop"
  template:
    metadata:
      labels:
        app: "ghworkshop"
    spec:
      containers:
        - name: "board-api"
          image: "acrghworkshop.azurecr.io/board-api"
          ports:
          - containerPort: 8090