apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghworkshop
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: ghworkshop.585f9e70f6c34ffcaf1f.koreacentral.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: ghworkshop
            port: 
              number: 8090