apiVersion: v1
kind: Service
metadata:
    name: "aksclusterghworkshop"
    labels:
        app: "ghworkshop"
spec:
    type: LoadBalancer
    ports:
    - port: 8090
      targetPort: 8091
      protocol: TCP
      name: http
    selector:
        app: "ghworkshop"
